### ISSUE TITLE
Question: How can I retrieve all active listings of a user?

### ISSUE THREAD

**Issue by kmob2** [flippa/flippa-js#40]
How can I retrieve all active listings of a user?

I am looking at https://developers.flippa.com/#list-all-listings but I can't seem to find anything.

I tried adding filter parameters for `https://api.flippa.com/v3/listings` such as:

`https://api.flippa.com/v3/listings?user_id=123456` and `https://api.flippa.com/v3/listings?seller=123456` (based on Flippa.com search parameter https://flippa.com/buy/search?seller=123456)

However none of them seem to work.

**Comment by JeanMarcGoepfert** [comment]
Hi @kmob2, you want to do: 

```
https://api.flippa.com/v3/listings?filter[user_id]=123456
```

**Comment by kmob2** [comment]
Perfect, that worked like a charm. Thank you so much.

By the way, would you know  if it's possible to retrieve "personal metrics" such as viewers and watchers of my auctions, if I authenticate myself with the API?

I tried to authenticate using "password grant" method (https://developers.flippa.com/?javascript#password-grant), along with my Flippa credentials and client_id as my Flippa ID, but I always received an error "invalid_client". I assume I would need to sign up for the Flippa API? If so, do you know where? Flippa support seemed to be confused when I mentioned the Flippa API and didn't know what I was talking about (could be that that particular support staff was not familiar with what an API is)

**Comment by JeanMarcGoepfert** [comment]
@kmob2 Unfortunately viewers and watchers of auctions is not something we support in our public api at the moment. 

For authentication, you'll need to get oauth credentials which we may provide depending on what you're using them for. Feel free to send an email to developers@flippa.com with some details about your project.
